// The offline bundle generated by `pnpm seed`. Always available — the game never needs Supabase to boot.
import pokemon from '@/data/pokemon.json'
import typeChart from '@/data/type-chart.json'
import diceTypes from '@/data/dice-types.json'
import areas from '@/data/areas.json'
import trainers from '@/data/trainers.json'
import upgrades from '@/data/upgrades.json'
import items from '@/data/items.json'
import config from '@/data/config.json'
import regions from '@/data/regions.json'
import type { BundleRaw } from '@/engine/types'

export const BUNDLE: BundleRaw = {
  pokemon,
  typeChart,
  diceTypes,
  areas,
  trainers,
  upgrades,
  items,
  config,
  regions,
} as unknown as BundleRaw
