import type { Row } from '@/config/mapping'

const NEEDS_QUOTE = /[",\n\r]/

function cell(v: unknown): string {
  if (v === null || v === undefined) return ''
  const s = typeof v === 'object' ? JSON.stringify(v) : String(v)
  return NEEDS_QUOTE.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

export function toCsv(rows: Row[], cols: string[]): string {
  return [cols.join(','), ...rows.map((r) => cols.map((c) => cell(r[c])).join(','))].join('\n')
}

function decode(s: string): unknown {
  if (s === '') return null
  if (/^(true|false|null)$/.test(s) || /^-?\d+(\.\d+)?$/.test(s) || /^[[{]/.test(s)) {
    try {
      return JSON.parse(s)
    } catch {
      return s
    }
  }
  return s
}

/** RFC 4180-ish parser; object/array/number/boolean cells are decoded back from JSON. */
export function parseCsv(text: string): Row[] {
  const records: string[][] = []
  let row: string[] = []
  let field = ''
  let quoted = false
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]!
    if (quoted) {
      if (ch === '"') {
        if (text[i + 1] === '"') {
          field += '"'
          i++
        } else quoted = false
      } else field += ch
    } else if (ch === '"') quoted = true
    else if (ch === ',') {
      row.push(field)
      field = ''
    } else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && text[i + 1] === '\n') i++
      row.push(field)
      records.push(row)
      row = []
      field = ''
    } else field += ch
  }
  if (field || row.length) {
    row.push(field)
    records.push(row)
  }
  const [header, ...body] = records.filter((r) => r.some((c) => c !== ''))
  if (!header) return []
  return body.map((r) => Object.fromEntries(header.map((h, i) => [h, decode(r[i] ?? '')])))
}

/** Trigger a browser download of a text file generated by the app itself. */
export function downloadText(filename: string, text: string, mime = 'text/plain') {
  const url = URL.createObjectURL(new Blob([text], { type: mime }))
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
